/**
 * /seeds/buildingAmen-seeds.js
 *
 * @description: seeds data for building amenities table
 *
 */

const { BuildingAmen } = require('../models');

const buildingAmenData = [
  {
    pets_allowed: true,
    roof: false,
    courtyard: false,
    concierge: false,
    doorman: false,
    elevator: false,
    laundry: false,
    children_playroom: false,
    gym: false,
    media_room: false,
    recreation_room: false,
    swimming_pool: false,
    live_in_super: false,
    smoke_free: false,
    wheelchair_access: false,
    garage_parking: false,
    valet_parking: false,
    bike_room: false,
    cold_storage: false,
    locker_cage: false,
    package_room: false,
    building_id: 1,
  },
  {
    pets_allowed: 'true',
    roof: false,
    courtyard: true,
    concierge: false,
    doorman: false,
    elevator: false,
    laundry: false,
    children_playroom: false,
    gym: false,
    media_room: false,
    recreation_room: false,
    swimming_pool: false,
    live_in_super: false,
    smoke_free: false,
    wheelchair_access: false,
    garage_parking: false,
    valet_parking: false,
    bike_room: false,
    cold_storage: false,
    locker_cage: false,
    package_room: false,
    building_id: 2,
  },
  {
    pets_allowed: 'true',
    roof: false,
    courtyard: true,
    concierge: false,
    doorman: false,
    elevator: false,
    laundry: false,
    children_playroom: false,
    gym: false,
    media_room: false,
    recreation_room: false,
    swimming_pool: false,
    live_in_super: false,
    smoke_free: false,
    wheelchair_access: false,
    garage_parking: false,
    valet_parking: false,
    bike_room: false,
    cold_storage: false,
    locker_cage: false,
    package_room: false,
    building_id: 3,
  },
  {
    pets_allowed: 'true',
    roof: false,
    courtyard: true,
    concierge: false,
    doorman: false,
    elevator: false,
    laundry: false,
    children_playroom: false,
    gym: false,
    media_room: false,
    recreation_room: false,
    swimming_pool: false,
    live_in_super: false,
    smoke_free: false,
    wheelchair_access: false,
    garage_parking: false,
    valet_parking: false,
    bike_room: false,
    cold_storage: false,
    locker_cage: false,
    package_room: false,
    building_id: 4,
  },
];

const seedBuildingAmen = () => BuildingAmen.bulkCreate(buildingAmenData);

module.exports = seedBuildingAmen;
